export const workbookFieldMap = Object.freeze({
  "Project Master.Project ID": "Project.projectId / Project.projectCode",
  "Project Master.Project Name": "Project.projectName",
  "Project Master.Customer / Funder": "Project.clientName",
  "Project Master.Business Line": "Project.businessLine",
  "Project Master.Project Manager": "Project.projectManager",
  "Project Master.Original Contract Value ($)": "Project.originalContractValue",
  "Project Crosswalk.Source ID / Code": "ProjectIdentifierCrosswalk.externalIdentifier",
  "Estimate Lines.Estimated Cost ($)": "EstimateLine.estimatedCost",
  "Estimate Lines.Quantity": "EstimateLine.quantity",
  "Estimate Lines.Unit": "EstimateLine.unit",
  "Labor Actuals.Hours": "LaborActual.hours",
  "Labor Actuals.Fully Burdened Labor Cost ($)": "LaborActual.fullyBurdenedLaborCost",
  "Nonlabor Actuals.Business Date": "NonlaborActual.businessDate",
  "Nonlabor Actuals.Accounting Date": "NonlaborActual.accountingDate",
  "Revenue & Billing.Invoice Amount ($)": "RevenueBillingRecord(invoice).amount",
  "Revenue & Billing.Revenue Recognized ($)": "RevenueBillingRecord(revenue-recognition).amount",
  "Revenue & Billing.Cash Collected ($)": "RevenueBillingRecord(cash-receipt).amount",
  "Change Orders.Additional Revenue ($)": "ChangeOrder.additionalRevenue",
  "Operational Drivers.Crew Days": "OperationalDriver.crewDays",
  "Grant Funding.Reimbursements Received ($)": "GrantFundingRecord.reimbursementsReceived",
  "Cost Code Map.Standard Cost Type": "CostCodeMapping.standardCostCategory",
  "Unmapped Exceptions.Exception Type": "DataException.exceptionType",
  "Project Summary.Estimate to Complete ($)": "ProjectFinancialSummary.estimatedCostToComplete",
  "Project Summary.Forecast / Final Cost ($)": "ProjectFinancialSummary.forecastFinalCost",
  "Benchmark Library.Low / P25": "Benchmark.low",
  "Benchmark Library.Median": "Benchmark.median",
  "Benchmark Library.High / P75": "Benchmark.high",
} as const);

export const workbookImportRules = Object.freeze([
  "Reject duplicate canonical project codes.",
  "Quarantine source rows without an approved project mapping.",
  "Keep business date and accounting date separate.",
  "Keep invoice, recognized revenue, cash, and reimbursement facts separate.",
  "Preserve both labor hours and fully burdened labor cost.",
  "Withhold forecast cost and margin when estimate to complete is missing.",
]);
